insert into Country (country_id, countryname) values ('1', 'Afghanistan');
insert into Country (country_id, countryname) values ('2', 'Albania');
insert into Country (country_id, countryname) values ('3', 'Algeria');
insert into Country (country_id, countryname) values ('4', 'Andorra');
insert into Country (country_id, countryname) values ('5', 'Angola');
insert into Country (country_id, countryname) values ('6', 'Antigua and Barbuda');
insert into Country (country_id, countryname) values ('7', 'Argentina');
insert into Country (country_id, countryname) values ('8', 'Armenia');
insert into Country (country_id, countryname) values ('9', 'Aruba');
insert into Country (country_id, countryname) values ('10', 'Australia');
insert into Country (country_id, countryname) values ('11', 'Austria');
insert into Country (country_id, countryname) values ('12', 'Azerbaijan');
insert into Country (country_id, countryname) values ('13', 'Bahamas');
insert into Country (country_id, countryname) values ('14', 'Bahrain');
insert into Country (country_id, countryname) values ('15', 'Bangladesh');
insert into Country (country_id, countryname) values ('16', 'Barbados');
insert into Country (country_id, countryname) values ('17', 'Belarus');
insert into Country (country_id, countryname) values ('18', 'Belgium');
insert into Country (country_id, countryname) values ('19', 'Belize');
insert into Country (country_id, countryname) values ('20', 'Benin');
insert into Country (country_id, countryname) values ('21', 'Bermuda');
insert into Country (country_id, countryname) values ('22', 'Bhutan');
insert into Country (country_id, countryname) values ('23', 'Bolivia');
insert into Country (country_id, countryname) values ('24', 'Bosnia and Herzegovina');
insert into Country (country_id, countryname) values ('25', 'Botswana');
insert into Country (country_id, countryname) values ('26', 'Brazil');
insert into Country (country_id, countryname) values ('27', 'Bulgaria');
insert into Country (country_id, countryname) values ('28', 'Burkina Faso');
insert into Country (country_id, countryname) values ('29', 'Burma');
insert into Country (country_id, countryname) values ('30', 'Burundi');
insert into Country (country_id, countryname) values ('31', 'Cambodia');
insert into Country (country_id, countryname) values ('32', 'Cameroon');
insert into Country (country_id, countryname) values ('33', 'Canada');
insert into Country (country_id, countryname) values ('34', 'Cape Verde');
insert into Country (country_id, countryname) values ('35', 'Central African Republic');
insert into Country (country_id, countryname) values ('36', 'Chad');
insert into Country (country_id, countryname) values ('37', 'Chile');
insert into Country (country_id, countryname) values ('38', 'China');
insert into Country (country_id, countryname) values ('39', 'Colombia');
insert into Country (country_id, countryname) values ('40', 'Congo');
insert into Country (country_id, countryname) values ('41', 'Costa Rica');
insert into Country (country_id, countryname) values ('42', 'CountryName');
insert into Country (country_id, countryname) values ('43', 'Croatia');
insert into Country (country_id, countryname) values ('44', 'Cuba');
insert into Country (country_id, countryname) values ('45', 'Cyprus');
insert into Country (country_id, countryname) values ('46', 'Czech Republic');
insert into Country (country_id, countryname) values ('47', 'Czechoslovakia');
insert into Country (country_id, countryname) values ('48', 'Democratic Republic of Congo');
insert into Country (country_id, countryname) values ('49', 'Democratic Republic of the Congo');
insert into Country (country_id, countryname) values ('50', 'Denmark');
insert into Country (country_id, countryname) values ('51', 'Djibouti');
insert into Country (country_id, countryname) values ('52', 'Dominica');
insert into Country (country_id, countryname) values ('53', 'Dominican Republic');
insert into Country (country_id, countryname) values ('54', 'East Germany');
insert into Country (country_id, countryname) values ('55', 'Ecuador');
insert into Country (country_id, countryname) values ('56', 'Egypt');
insert into Country (country_id, countryname) values ('57', 'El Salvador');
insert into Country (country_id, countryname) values ('58', 'Eritrea');
insert into Country (country_id, countryname) values ('59', 'Estonia');
insert into Country (country_id, countryname) values ('60', 'Ethiopia');
insert into Country (country_id, countryname) values ('61', 'Faroe Islands');
insert into Country (country_id, countryname) values ('62', 'Federal Republic of Yugoslavia');
insert into Country (country_id, countryname) values ('63', 'Federated States of Micronesia');
insert into Country (country_id, countryname) values ('64', 'Fiji');
insert into Country (country_id, countryname) values ('65', 'Finland');
insert into Country (country_id, countryname) values ('66', 'France');
insert into Country (country_id, countryname) values ('67', 'French Guiana');
insert into Country (country_id, countryname) values ('68', 'Gabon');
insert into Country (country_id, countryname) values ('69', 'Gambia');
insert into Country (country_id, countryname) values ('70', 'Georgia');
insert into Country (country_id, countryname) values ('71', 'Germany');
insert into Country (country_id, countryname) values ('72', 'Ghana');
insert into Country (country_id, countryname) values ('73', 'Gibraltar');
insert into Country (country_id, countryname) values ('74', 'Greece');
insert into Country (country_id, countryname) values ('75', 'Greenland');
insert into Country (country_id, countryname) values ('76', 'Grenada');
insert into Country (country_id, countryname) values ('77', 'Guadeloupe');
insert into Country (country_id, countryname) values ('78', 'Guam');
insert into Country (country_id, countryname) values ('79', 'Guatemala');
insert into Country (country_id, countryname) values ('80', 'Guinea');
insert into Country (country_id, countryname) values ('81', 'Guinea-Bissau');
insert into Country (country_id, countryname) values ('82', 'Guyana');
insert into Country (country_id, countryname) values ('83', 'Haiti');
insert into Country (country_id, countryname) values ('84', 'Honduras');
insert into Country (country_id, countryname) values ('85', 'Hong Kong');
insert into Country (country_id, countryname) values ('86', 'Hungary');
insert into Country (country_id, countryname) values ('87', 'Iceland');
insert into Country (country_id, countryname) values ('88', 'India');
insert into Country (country_id, countryname) values ('89', 'Indonesia');
insert into Country (country_id, countryname) values ('90', 'Iran');
insert into Country (country_id, countryname) values ('91', 'Iraq');
insert into Country (country_id, countryname) values ('92', 'Ireland');
insert into Country (country_id, countryname) values ('93', 'Israel');
insert into Country (country_id, countryname) values ('94', 'Italy');
insert into Country (country_id, countryname) values ('95', 'Ivory Coast');
insert into Country (country_id, countryname) values ('96', 'Jamaica');
insert into Country (country_id, countryname) values ('97', 'Japan');
insert into Country (country_id, countryname) values ('98', 'Jordan');
insert into Country (country_id, countryname) values ('99', 'Kazakhstan');
insert into Country (country_id, countryname) values ('100', 'Kenya');
insert into Country (country_id, countryname) values ('101', 'Kiribati');
insert into Country (country_id, countryname) values ('102', 'Korea');
insert into Country (country_id, countryname) values ('103', 'Kosovo');
insert into Country (country_id, countryname) values ('104', 'Kuwait');
insert into Country (country_id, countryname) values ('105', 'Kyrgyzstan');
insert into Country (country_id, countryname) values ('106', 'Laos');
insert into Country (country_id, countryname) values ('107', 'Latvia');
insert into Country (country_id, countryname) values ('108', 'Lebanon');
insert into Country (country_id, countryname) values ('109', 'Lesotho');
insert into Country (country_id, countryname) values ('110', 'Liberia');
insert into Country (country_id, countryname) values ('111', 'Libya');
insert into Country (country_id, countryname) values ('112', 'Liechtenstein');
insert into Country (country_id, countryname) values ('113', 'Lithuania');
insert into Country (country_id, countryname) values ('114', 'Luxembourg');
insert into Country (country_id, countryname) values ('115', 'Macao');
insert into Country (country_id, countryname) values ('116', 'Macau');
insert into Country (country_id, countryname) values ('117', 'Madagascar');
insert into Country (country_id, countryname) values ('118', 'Malawi');
insert into Country (country_id, countryname) values ('119', 'Malaysia');
insert into Country (country_id, countryname) values ('120', 'Maldives');
insert into Country (country_id, countryname) values ('121', 'Mali');
insert into Country (country_id, countryname) values ('122', 'Malta');
insert into Country (country_id, countryname) values ('123', 'Martinique');
insert into Country (country_id, countryname) values ('124', 'Mauritania');
insert into Country (country_id, countryname) values ('125', 'Mauritius');
insert into Country (country_id, countryname) values ('126', 'Mexico');
insert into Country (country_id, countryname) values ('127', 'Moldova');
insert into Country (country_id, countryname) values ('128', 'Monaco');
insert into Country (country_id, countryname) values ('129', 'Mongolia');
insert into Country (country_id, countryname) values ('130', 'Montenegro');
insert into Country (country_id, countryname) values ('131', 'Montserrat');
insert into Country (country_id, countryname) values ('132', 'Morocco');
insert into Country (country_id, countryname) values ('133', 'Mozambique');
insert into Country (country_id, countryname) values ('134', 'Myanmar');
insert into Country (country_id, countryname) values ('135', 'Namibia');
insert into Country (country_id, countryname) values ('136', 'Nepal');
insert into Country (country_id, countryname) values ('137', 'Netherlands');
insert into Country (country_id, countryname) values ('138', 'Netherlands Antilles');
insert into Country (country_id, countryname) values ('139', 'New Caledonia');
insert into Country (country_id, countryname) values ('140', 'New Zealand');
insert into Country (country_id, countryname) values ('141', 'Nicaragua');
insert into Country (country_id, countryname) values ('142', 'Niger');
insert into Country (country_id, countryname) values ('143', 'Nigeria');
insert into Country (country_id, countryname) values ('144', 'Niue');
insert into Country (country_id, countryname) values ('145', 'North Korea');
insert into Country (country_id, countryname) values ('146', 'North Vietnam');
insert into Country (country_id, countryname) values ('147', 'Norway');
insert into Country (country_id, countryname) values ('148', 'Occupied Palestinian Territory');
insert into Country (country_id, countryname) values ('149', 'Oman');
insert into Country (country_id, countryname) values ('150', 'Pakistan');
insert into Country (country_id, countryname) values ('151', 'Palau');
insert into Country (country_id, countryname) values ('152', 'Palestine');
insert into Country (country_id, countryname) values ('153', 'Panama');
insert into Country (country_id, countryname) values ('154', 'Papua New Guinea');
insert into Country (country_id, countryname) values ('155', 'Paraguay');
insert into Country (country_id, countryname) values ('156', 'Peru');
insert into Country (country_id, countryname) values ('157', 'Philippines');
insert into Country (country_id, countryname) values ('158', 'Poland');
insert into Country (country_id, countryname) values ('159', 'Portugal');
insert into Country (country_id, countryname) values ('160', 'Puerto Rico');
insert into Country (country_id, countryname) values ('161', 'Qatar');
insert into Country (country_id, countryname) values ('162', 'Republic of Macedonia');
insert into Country (country_id, countryname) values ('163', 'Reunion');
insert into Country (country_id, countryname) values ('164', 'Romania');
insert into Country (country_id, countryname) values ('165', 'Russia');
insert into Country (country_id, countryname) values ('166', 'Rwanda');
insert into Country (country_id, countryname) values ('167', 'Saint Vincent and the Grenadines');
insert into Country (country_id, countryname) values ('168', 'Samoa');
insert into Country (country_id, countryname) values ('169', 'San Marino');
insert into Country (country_id, countryname) values ('170', 'Saudi Arabia');
insert into Country (country_id, countryname) values ('171', 'Senegal');
insert into Country (country_id, countryname) values ('172', 'Serbia');
insert into Country (country_id, countryname) values ('173', 'Serbia and Montenegro');
insert into Country (country_id, countryname) values ('174', 'Seychelles');
insert into Country (country_id, countryname) values ('175', 'Siam');
insert into Country (country_id, countryname) values ('176', 'Sierra Leone');
insert into Country (country_id, countryname) values ('177', 'Singapore');
insert into Country (country_id, countryname) values ('178', 'Slovakia');
insert into Country (country_id, countryname) values ('179', 'Slovenia');
insert into Country (country_id, countryname) values ('180', 'Somalia');
insert into Country (country_id, countryname) values ('181', 'South Africa');
insert into Country (country_id, countryname) values ('182', 'South Korea');
insert into Country (country_id, countryname) values ('183', 'Soviet Union');
insert into Country (country_id, countryname) values ('184', 'Spain');
insert into Country (country_id, countryname) values ('185', 'Sri Lanka');
insert into Country (country_id, countryname) values ('186', 'Sudan');
insert into Country (country_id, countryname) values ('187', 'Suriname');
insert into Country (country_id, countryname) values ('188', 'Swaziland');
insert into Country (country_id, countryname) values ('189', 'Sweden');
insert into Country (country_id, countryname) values ('190', 'Switzerland');
insert into Country (country_id, countryname) values ('191', 'Syria');
insert into Country (country_id, countryname) values ('192', 'Taiwan');
insert into Country (country_id, countryname) values ('193', 'Tajikistan');
insert into Country (country_id, countryname) values ('194', 'Tanzania');
insert into Country (country_id, countryname) values ('195', 'Thailand');
insert into Country (country_id, countryname) values ('196', 'Togo');
insert into Country (country_id, countryname) values ('197', 'Tonga');
insert into Country (country_id, countryname) values ('198', 'Trinidad and Tobago');
insert into Country (country_id, countryname) values ('199', 'Tunisia');
insert into Country (country_id, countryname) values ('200', 'Turkey');
insert into Country (country_id, countryname) values ('201', 'Turkmenistan');
insert into Country (country_id, countryname) values ('202', 'U.S. Virgin Islands');
insert into Country (country_id, countryname) values ('203', 'UK');
insert into Country (country_id, countryname) values ('204', 'USA');
insert into Country (country_id, countryname) values ('205', 'Uganda');
insert into Country (country_id, countryname) values ('206', 'Ukraine');
insert into Country (country_id, countryname) values ('207', 'United Arab Emirates');
insert into Country (country_id, countryname) values ('208', 'Uruguay');
insert into Country (country_id, countryname) values ('209', 'Uzbekistan');
insert into Country (country_id, countryname) values ('210', 'Venezuela');
insert into Country (country_id, countryname) values ('211', 'Vietnam');
insert into Country (country_id, countryname) values ('212', 'West Germany');
insert into Country (country_id, countryname) values ('213', 'Western Sahara');
insert into Country (country_id, countryname) values ('214', 'Yemen');
insert into Country (country_id, countryname) values ('215', 'Yugoslavia');
insert into Country (country_id, countryname) values ('216', 'Zaire');
insert into Country (country_id, countryname) values ('217', 'Zambia');
insert into Country (country_id, countryname) values ('218', 'Zimbabwe');


